make seeder
Jooyeshgar/FreeAmir pull request #10
Opened 2024-04-02 20:32 UTC by fdaei

2024-04-03 06:39 UTC, hadi60 requested changes

2024-04-03 06:39 UTC, hadi60 commented on database/seeders/BankSeeder.php
> +            ['Id' => 9, 'Name' => 'ملی', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]
بانک ملّی ایران
بانک سپه
بانک صنعت و معدن
بانک کشاورزی
بانک مسکن
بانک توسعه صادرات ایران
بانک توسعه تعاون
پست بانک ایران
بانک اقتصاد نوین
بانک پارسیان
بانک کارآفرین
بانک سامان
بانک سینا
بانک خاورمیانه
بانک شهر
بانک دی
بانک صادرات
بانک ملت
بانک تجارت
بانک رفاه
بانک آینده
بانک گردشگری
بانک ایران زمین
بانک سرمایه
بانک پاسارگاد

2024-04-03 06:39 UTC, hadi60 commented on database/seeders/ConfigSeeder.php
> +             ['key' => 'config1', 'value' => 'value1', 'desc' => 'description1', 'type' => 'type1', 'category' => 'category1'],
{'id' : 1, 'Type' : 1, 'Cat' : 0, 'Key' : 'co-name' , 'Vale' : 'Enter Company Name','Desc' : 'Enter Company name here'},
{'id' : 2, 'Type' : 0, 'Cat' : 0, 'Key' : 'co-logo' , 'Vale' : '','Desc' : 'Select Colpany logo'},
{'id' : 3, 'Type' : 2, 'Cat' : 1, 'Key' : 'custSubject' , 'Vale' : '4','Desc' : 'Enter here'},
{'id' : 4, 'Type' : 3, 'Cat' : 1, 'Key' : 'bank' , 'Vale' : '1','Desc' : 'Enter here'},
{'id' : 5, 'Type' : 3, 'Cat' : 1, 'Key' : 'cash' , 'Vale' : '3','Desc' : 'Enter here'},
{'id' : 6, 'Type' : 3, 'Cat' : 1, 'Key' : 'buy' , 'Vale' : '17','Desc':'Enter here'},
{'id' : 7, 'Type' : 3, 'Cat' : 1, 'Key' : 'sell' , 'Vale' : '18','Desc':'Enter here'},
{'id' : 8, 'Type' : 2, 'Cat' : 1, 'Key' : 'sell-discount' , 'Vale' : '25','Desc':'Enter here'},
{'id' : 9, 'Type' : 3, 'Cat' : 1, 'Key' : 'tax' , 'Vale' : '33','Desc':'Enter here'},
{'id' :10, 'Type' : 3, 'Cat' : 1, 'Key' : 'partners' , 'Vale' : '8','Desc':'Enter here'},
{'id' :11, 'Type' : 3, 'Cat' : 1, 'Key' : 'cost' , 'Vale' : '2','Desc':'Enter here'},
{'id' :12, 'Type' : 2, 'Cat' : 1, 'Key' : 'bank-wage' , 'Vale' : '31','Desc':'Enter here'},
{'id' :13, 'Type' : 3, 'Cat' : 1, 'Key' : 'our_cheque' , 'Vale' : '22','Desc' :'Enter here'},
{'id' :14, 'Type' : 3, 'Cat' : 1, 'Key' : 'other_cheque' , 'Vale' : '6','Desc' :'Enter here'},
{'id' :15, 'Type' : 3, 'Cat' : 1, 'Key' : 'income' , 'Vale' : '83','Desc':'Enter here'}
{'id' :11, 'Type' : 3, 'Cat' : 1, 'Key' : 'fund' , 'Vale' : '??', 'Desc':'Enter here'},
{'id' :12, 'Type' : 3, 'Cat' : 1, 'Key' : 'acc-receivable', 'Vale' : '??', 'Desc':'Enter here',},
{'id' :13, 'Type' : 3, 'Cat' : 1, 'Key' : 'commission' , 'Vale' : '??', 'Desc':'Enter here'}

2024-04-03 06:39 UTC, hadi60 commented on database/seeders/BankAccountSeeder.php
> +            ['Id' => 1, 'name' => 'Account 1', 'number' => '123456789', 'type' => 1, 'owner' => 'John Doe', 'bank_id' => DB::table('banks')->where('Name', 'پارسیان')->first()->id, 'bank_branch' => 'M
در مواردی که داده ها واقعی باشه ما از این روش استفاده می کنیم مثلا اسم بانک ها که ثابت هستند در مواقعی که دیتاها الکی هستند از factory استفاده می کنن
https://laravel.com/docs/11.x/eloquent-factories
شما اول باید یه فاکتوری بسازی بعد با اون هر تعدا دخواستی اکانت ایجاد کنی
```
public function run(): void
{
    User::factory()
            ->count(50)
            ->hasPosts(1)
            ->create();
}
```

2024-04-06 12:51 UTC, DNAliyari commented on database/seeders/BankSeeder.php
> +            ['Id' => 19, 'Name' => 'بانک پارسیان', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
- بانک ها با نام های تکراری وجود دارند
- نام بانک ها با یک فرمت یکسان قرار داده شود ( بانک ... )
- فیلد name در مدل Bank با حروف کوچک نوشته شده است
- فیلد های created_at و updated_at را میتوان حذف کرد و به جای آن در مدل خط زیر را حذف کرد تا به صورت اتوماتیک این ۲ فیلد مقدار دهی شوند :     public $timestamps = false;
- فیلد Id نیاز به تعریف ندارد و با insert کردن دیتا خودبخود این مقدار وارد می شود

2024-04-06 12:51 UTC, DNAliyari commented on database/seeders/BankSeeder.php
> +        DB::table('banks')->insert($subjectData);
بهتر است از insert خود eloquent استفاده کرد : 
Bank::insert($subjectData);

2024-04-06 12:51 UTC, DNAliyari commented on database/seeders/BankAccountSeeder.php
> +                'created_at' => Carbon::now(),
در صورتی که در مدل BankAccount کد زیر را حذف کنید نیاز به تعریف created_at و updated_at نیست. 
public $timestamps = false;

2024-04-06 12:51 UTC, DNAliyari commented on database/seeders/ConfigSeeder.php
> +            ['id' => 1, 'type' => 1, 'category' => 0, 'key' => 'co-name', 'value' => 'Enter Company Name', 'desc' => 'Enter Company name here'],
در صورتی که کد زیر را از مدل Config حذف کنید نیاز به اضافه کردن id نیست و به صورت اتوماتیک آیدی اضافه می شود
    public $incrementing = false;

2024-04-06 12:51 UTC, DNAliyari commented on database/seeders/ConfigSeeder.php
> +        DB::table('configs')->insert($configs);
بهتره از eloquent استفاده شود 
Config::insert($configs);

2024-04-06 12:51 UTC, DNAliyari commented on database/seeders/CustomerGroupSeeder.php
> +            ['id' => 1, 'code' => 'general', 'name' => 'عمومی', 'description' => 'گروه مشتریان عمومی'],
فیلد id نیاز به تعریف ندارد و با insert کردن دیتا خودبخود این مقدار وارد می شود

2024-04-06 12:51 UTC, DNAliyari commented on database/seeders/CustomerGroupSeeder.php
> +        DB::table('customer_groups')->insert($customerGroups);
بهتره از eloquent استفاده شود
CustomerGroup::insert($customerGroups);

2024-04-06 12:51 UTC, DNAliyari commented on database/factories/CustomerFactory.php
> +            'subject_id' => $this->faker->randomElement(DB::table('subjects')->pluck('id')->toArray()),
بهتر است از eloquent استفاده شود

2024-04-06 12:51 UTC, DNAliyari commented on database/factories/CustomerFactory.php
> +            'introducer_id' => $this->faker->randomElement(DB::table('customers')->pluck('id')->toArray()),
بهتر است از eloquent استفاده شود

2024-04-06 12:51 UTC, DNAliyari commented on database/seeders/ProductGroupSeeder.php
> +            ['id' => 1, 'code' => 'general', 'name' => 'عمومی', 'buyId' => 1, 'sellId' => 1],
نیاز به تعریف id نیست

2024-04-06 12:51 UTC, DNAliyari commented on database/seeders/ProductGroupSeeder.php
> +        DB::table('product_groups')->insert($productGroups);
بهتره از eloquent استفاده شود

2024-04-13 06:12 UTC, DNAliyari commented on database/seeders/BankSeeder.php
> +            ['name' => 'بانک پارسیان'],
همچنان نام های تکراری وجود دارند.
توی کامنت قبلی این مورد رو گفته بودم

2024-04-13 06:12 UTC, DNAliyari commented on database/factories/CustomerFactory.php
> +            'subject_id' => $this->faker->randomElement(Customer::pluck('id')->toArray()),
اینجا مدل Subject باید استفاده میشد
کد قبلی به این شکل بود که قرار شد از خود مدل استفاده شود:
DB::table('subjects')->pluck('id')->toArray()

2024-04-15 04:54 UTC, merged